### PR TITLE
Faketips removal

### PR DESCRIPTION
**Pull request by crossexonar**
Requested by lasagna-wolf, Purges the tips system as its been giving Vore-Station specific guidelines.

### CODE REVIEW

**Comment by Michab02** [comment]
Is purging the system entirely preferable to updating it?

**Comment by FartMaster69420** [comment]
It is what the dark lord demands of us.

**Comment by crossexonar** [comment]
:lasagna:

**Comment by lm40** [comment]
In my opinion yes, while the idea behind it is laudable it is not really a very effective system for teaching anyone anything.

**Review by lm40 — APPROVED** [review]

**Pull request merged**
