### PR TITLE
[DNM] MKII Hypo Rework 2 Electric Boogaloo.

### PR DESCRIPTION
**Pull request by crossexonar**
Based on feedback gained from: https://github.com/TS-Rogue-Star/Rogue-Star/pull/489
Hello MEDICAL players, I seek to improve the gameplay of the Mk2 Hyposprays.
Featured here: 
Simple hot-Swapping of vials in containers (belts or boxes)
Adjustable injection rate toggles (It already existed on the vials, now you can override them on the hypo if you want)
Proper Box selection for MK1 and Mk2 Hyposprays (depending on your preference)
Injection Time is based on how much you're injecting, and which Hypospray you're using.
Improved sizing of hypovials to match their older counterparts (30u ones are tiny, 60u ones are the size of a bottle)
You can wear the hypokits on your belt slot, to fully dedicate yourself to the hypospray 'meta' (not actually a meta)
Controversial things:
Added some empty kits that come with a hypo and some empty vials to Medical vendors
Removed the pre-filled hypokits from the Medical vendors, You gotta order em from cargo if you -really- want em
The kits from cargo are CHEAP, 25 points (cargo starts with 50 points), and come with 2 of each kind of kit.

Not added yet, but could be:
Bluespace versions of the vials. Double the capacity, same space, wowie gee batman

I value your feedback on this matter and have a test server available if you wish to try them out yourself.

In the end, these may prove TOO good to just give round-start and may either need a nerf, or be restricted to only cargo ordering.

And thank you pooj for providing these in the first place, aswell as give me motivation to make them more desireable to medical players.

### CODE REVIEW

**Comment by crossexonar** [comment]
(oh god something is going weird with the maps, kill me)

**Comment by Zoldorf** [comment]
I'd honestly just want to go back to the regular Hypospray of old, but this is a good substitute, though should be limited from roundstart.

**Comment by crossexonar** [comment]
> I'd honestly just want to go back to the regular Hypospray of old, but this is a good substitute, though should be limited from roundstart.

The hypospray of old is still in there dork, Could you please elaborate as to why it should be limited from round-start?
They're only really as good as syringes with a bit more ability to fine tune, sacrificing bottles for vials that have less capacity, take up room on belt slot, or you have to sacrifice your blet slot dedicate yourself directly to the hypospray kit to be able to carry a decent amount of chems.

**Comment by LanderExqueak** [comment]
After testing and fiddling with this thing a bit, it seems useful enough that I'd say it should probably either be orderable from Cargo, or craftable piecemeal by Science. It's very good, to the point it genuinely makes syringes feel outright inferior in comparison.

**Comment by crossexonar** [comment]
> After testing and fiddling with this thing a bit, it seems useful enough that I'd say it should probably either be orderable from Cargo, or craftable piecemeal by Science. It's very good, to the point it genuinely makes syringes feel outright inferior in comparison.

The CMO one specifically? or the normal ones, you do have to compare them fairly as command gear tends to be overall better.

**Comment by LanderExqueak** [comment]
> > After testing and fiddling with this thing a bit, it seems useful enough that I'd say it should probably either be orderable from Cargo, or craftable piecemeal by Science. It's very good, to the point it genuinely makes syringes feel outright inferior in comparison.
> 
> The CMO one specifically? or the normal ones, you do have to compare them fairly as command gear tends to be overall better.

The CMO one, yes, sorry and thank you for getting clarification.

**Pull request closed without merging**
