### PR TITLE
Fixes collar descriptions

### PR DESCRIPTION
**Pull request by Arokha**
Probably! Untested.

### CODE REVIEW

**Review by lm40 — DISMISSED** [review]

**Comment by lm40** [comment]
Probably.

**Comment by Arokha** [comment]
Probably! Lex/Rykka said she'd help test later so I'd just leave this alone until then.

**Comment by lm40** [comment]
So actually it doesn't work on spawn only on rename, therefore I will RETRACT my approval.

**Comment by Arokha** [comment]
Got un-lazy and set up a test environment. Fixed issue with spawning, tested spawning, renaming, etc.
I also removed the loadout 'name' customization, as it has never worked (it's created procedurally). It seems like a bad idea to have anyway.

**Review by lm40 — APPROVED** [review]

**Pull request merged**
